version: '3.8'

services:
  owomizu:
    build: .
    container_name: owomizu
    restart: unless-stopped
    ports:
      - "1200:1200"
    volumes:
      - ./config:/app/config
      - ./utils/data:/app/utils/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
